name: PHP Tests

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'

      - name: Install PHPUnit
        run: |
          wget https://phar.phpunit.de/phpunit-9.6.phar -O phpunit
          chmod +x phpunit
          sudo mv phpunit /usr/local/bin/phpunit

      - name: Run PHPUnit tests
        run: phpunit --testdox test/
