name: PHP Tests

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'

      - name: Install PHPUnit
        run: |
          wget https://phar.phpunit.de/phpunit-9.6.phar -O phpunit
          chmod +x phpunit
          sudo mv phpunit /usr/local/bin/phpunit

      - name: Start PHP built-in server
        run: php -S localhost:8000 -t . &
        # 👆 Usa '.' si tu index.php está en la raíz
        #    Si está en /public pon "-t public/"

      - name: Run PHPUnit tests
        run: phpunit --testdox tests/
